"""init_models

Revision ID: ff24614274c8
Revises:
Create Date: 2026-02-20 13:35:17.996497

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff24614274c8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("name", sa.String(), nullable=False, comment="Artist's name"),
        sa.Column("bio", sa.Text(), nullable=True, comment="Artist's biography"),
        sa.Column(
            "image_url",
            sa.String(),
            nullable=True,
            comment="Image's url in minio",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_artists_uuid"), "artists", ["uuid"], unique=False)
    op.create_table(
        "genres",
        sa.Column("name", sa.String(), nullable=False, comment="Genre's title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Genre's description",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_genres_uuid"), "genres", ["uuid"], unique=False)
    op.create_table(
        "albums",
        sa.Column("name", sa.String(), nullable=False, comment="Album's title"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Album's description",
        ),
        sa.Column(
            "cover_url",
            sa.String(),
            nullable=True,
            comment="Cover's url in minio",
        ),
        sa.Column(
            "artist_uuid",
            sa.UUID(),
            nullable=False,
            comment="Artist's unique id",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["artist_uuid"],
            ["artists.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_albums_artist_uuid"), "albums", ["artist_uuid"], unique=False
    )
    op.create_index(op.f("ix_albums_uuid"), "albums", ["uuid"], unique=False)
    op.create_table(
        "album_genres",
        sa.Column("album_uuid", sa.UUID(), nullable=False),
        sa.Column("genre_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["album_uuid"],
            ["albums.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_uuid"],
            ["genres.uuid"],
        ),
        sa.PrimaryKeyConstraint("album_uuid", "genre_uuid", "uuid"),
        sa.UniqueConstraint("album_uuid", "genre_uuid", name="idx_unique_album_genre"),
    )
    op.create_index(
        op.f("ix_album_genres_uuid"), "album_genres", ["uuid"], unique=False
    )
    op.create_table(
        "tracks",
        sa.Column("name", sa.String(), nullable=False, comment="Track's title"),
        sa.Column(
            "duration",
            sa.Integer(),
            nullable=False,
            comment="Track's duration",
        ),
        sa.Column(
            "audio_url",
            sa.String(),
            nullable=True,
            comment="Audio's url in minio",
        ),
        sa.Column("bitrate", sa.String(), nullable=False, comment="Track's bitrate"),
        sa.Column(
            "format",
            sa.Enum("MP3", "FLAC", "AAC", name="trackformat"),
            nullable=False,
            comment="Track's format",
        ),
        sa.Column(
            "artist_uuid",
            sa.UUID(),
            nullable=False,
            comment="Artist's unique id",
        ),
        sa.Column(
            "album_uuid",
            sa.UUID(),
            nullable=False,
            comment="Album's unique id",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["album_uuid"],
            ["albums.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_uuid"],
            ["artists.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_tracks_album_uuid"), "tracks", ["album_uuid"], unique=False
    )
    op.create_index(
        op.f("ix_tracks_artist_uuid"), "tracks", ["artist_uuid"], unique=False
    )
    op.create_index(op.f("ix_tracks_uuid"), "tracks", ["uuid"], unique=False)
    op.create_table(
        "track_genres",
        sa.Column("track_uuid", sa.UUID(), nullable=False),
        sa.Column("genre_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["genre_uuid"],
            ["genres.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["track_uuid"],
            ["tracks.uuid"],
        ),
        sa.PrimaryKeyConstraint("track_uuid", "genre_uuid", "uuid"),
        sa.UniqueConstraint("track_uuid", "genre_uuid", name="idx_unique_track_genre"),
    )
    op.create_index(
        op.f("ix_track_genres_uuid"), "track_genres", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_track_genres_uuid"), table_name="track_genres")
    op.drop_table("track_genres")
    op.drop_index(op.f("ix_tracks_uuid"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_artist_uuid"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_album_uuid"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_album_genres_uuid"), table_name="album_genres")
    op.drop_table("album_genres")
    op.drop_index(op.f("ix_albums_uuid"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist_uuid"), table_name="albums")
    op.drop_table("albums")
    op.drop_index(op.f("ix_genres_uuid"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_artists_uuid"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
